repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.11
    hooks:
      - id: ruff-check
        types_or: [python, pyi]
        args: [--fix, --select, "E,W,F,I,B,C4,SIM", --line-length, "120"]
      - id: ruff-format
        types_or: [python, pyi]
        args: [--line-length, "120"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
        language_version: python3.12
