[project]
name = "vir-chatbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
]

[dependency-groups]
dev = [
    "google==3.0.0",
    "langchain==1.1.0",
    "langchain-community>=0.3.28",
    "langchain-core==1.1.0",
    "langchain-google-genai==3.2.0",
    "langchain-google-vertexai==3.1.0",
    "pydantic-settings==2.11.0",
    "ipykernel==7.1.0",
    "pip==25.3",
    "faiss-cpu==1.12.0",
    "langchain-docling==2.0.0",
    "docling==2.61.1",
    "langgraph-checkpoint-sqlite==3.0.0",
    "langgraph==1.0.4",
    "streamlit==1.51.0",
    "langgraph-cli[inmem]==0.4.3"
]

[tool.isort]
profile = "black"
